server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: native, vault
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
          order: 1

        vault:
          host: 127.0.0.1
          port: 8200
          authentication: TOKEN
          token: myroot
          kv-version: 2
          order: 2
